image: python:3.7

stages:
  - linter
  - test
  - build
  - release

before_script:
  - pip -V
  - pip install -U pip

linter:
  stage: linter
  allow_failure: true
  script:
    - pip install tox
    - tox -e linter

test:
  stage: test
  script:
    - pip install tox
    - tox -e py37

build:
  stage: build
  script:
    - pip install twine
    - make build
    - twine check dist/*
    - make install
    - cicflowmeter -h

release:
  stage: release
  script:
    - pip install twine
    - make build
    - twine upload dist/* -u "__token__" -p $TWINE_TOKEN
  when: manual
  only:
    - tags
