image: python:3.7

stages:
  - linter
  - test
  - build
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install -U pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install tox, twine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/
    - .tox/
    - venv/

linter:
  stage: linter
  allow_failure: true
  script:
    - tox -e linter

test:
  stage: test
  script:
    - tox -e py37

build:
  stage: build
  script:
    - make build
    - tox -e pypi
    - make install
    - cicflowmeter -h
  artifacts:
    paths:
      - dist/

release:
  stage: release
  script:
    - twine upload dist/* -u "__token__" -p $TWINE_TOKEN
  when: manual
  artifacts:
    paths:
      - dist
  only:
    - tags
